// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
  aws_project_region: 'us-east-1',
  aws_cognito_identity_pool_id: 'us-east-1:df597bdd-b3f6-4f65-ad10-2dec51327f1a',
  aws_cognito_region: 'us-east-1',
  aws_user_pools_id: 'us-east-1_UyeghTuhu',
  aws_user_pools_web_client_id: 'k2j5350pitmjb1pejld3na4al',
  oauth: {
    domain: '1635820993147-timesheets',
    scope: ['phone', 'email', 'profile', 'openid', 'aws.cognito.signin.user.admin'],
    redirectSignIn: 'http://localhost:3000/',
    redirectSignOut: 'http://localhost:3000/',
    responseType: 'token' // or 'token', note that REFRESH token will only be generated when the responseType is code
  }
}

export default awsmobile
